# This is an example Starter pipeline configuration
# Use a skeleton to build, test and deploy using manual and parallel steps
# -----
# You can specify a custom docker image from Docker Hub as your build environment.

image: node:lts-alpine

options:
  cache:
    paths:
      - ./frontend/node_modules
      - ./backend/node_modules
  docker: true

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test the Frontend'
          script:
            - apk add --no-cache docker-compose
            - docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build --exit-code-from next-app-test
      - step:
          name: 'Build and Test Backend'
          script:
            - apk add --no-cache docker-compose
            - docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build --exit-code-from backend-test
