services:
  next-app-test:
    build:
      context: ./frontend
      dockerfile: production.Dockerfile
    command: sh -c "corepack enable && corepack prepare yarn@stable --activate && yarn && yarn run build && yarn run lint && yarn run test"
    environment:
      - NODE_ENV=test

  backend-test:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: sh -c "corepack enable && corepack prepare yarn@stable --activate && yarn && yarn run lint && yarn run build && node ace migration:run && yarn run test"
    environment:
      - NODE_ENV=test

networks:
  my_network:
    external: true
